version: '3.8'

services:
  backend:
    build: ./backend/
    ports:
      - "5001:5001"

  frontend:
    build: ./frontend/
    ports:
      - "8080:8080"
    depends_on:
      - backend
